### PR TITLE
Bug/bytes to varchar

### PR DESCRIPTION
**Pull request by ana0**

### CODE REVIEW

**Review by i-norden — APPROVED** [review]
LGTM!!

**Comment by i-norden** [comment]
When you say unit tests I assume you are referring to the integration_tests? I don't think we have unit tests for this stuff yet.

**Comment by ana0** [comment]
> When you say unit tests I assume you are referring to the integration_tests? I don't think we have unit tests for this stuff yet.

Hmm, I was misunderstanding how the tests were run. There's a new commit now that has the integration tests *actually* running

**Comment by i-norden** [comment]
Thank you! Sorry I didn't catch that. We should get CI setup for this repo, that would help with catching stuff like this.

Also I'm wondering what the long term prospects of this repository are? Is there a VeriLedger repo for branching off work specific to them or is this going to remain their staging repo? I need to take this work in a somewhat different direction to support BlockScout (e.g. they use BYTEA).

**Comment by ana0** [comment]
Closing and recreating in the veriledger repo

**Pull request closed without merging**
